# Generated by Django 3.0 on 2019-12-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gho', models.CharField(max_length=220)),
                ('year', models.PositiveIntegerField(default=2019)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both sexes', 'Both sexes')], max_length=10)),
                ('number_of_years', models.FloatField()),
                ('region', models.CharField(choices=[('Global', 'Global'), ('Africa', 'Africa'), ('Americas', 'Americas'), ('South-East Asia', 'South-East Asia'), ('Europe', 'Europe'), ('Eastern Mediterranean', 'Eastern Mediterranean'), ('Western Pacific', 'Western Pacific')], max_length=50)),
            ],
            options={
                'unique_together': {('region', 'year', 'gho', 'gender')},
            },
        ),
    ]
